<?php
$orgs = array(
        "Organization"=>"Organization",
        "LocalBusiness"=>"Local Business",
        "Airline"=>"Airline",
        "EducationalOrganization"=>"Educational Organization",
        "GovernmentOrganization"=>"Government Organization",
        "NGO"=>"Non-government Organization",
        "PerformingGroup"=>"Performing Group",
        "AnimalShelter"=>"Animal Shelter",
        "AutomotiveBusiness"=>"Automotive Business",
        "ChildCare"=>"Child Care",
        "DryCleaningOrLaundry"=>"Dry Cleaning or Laundry",
        "EmergencyService"=>"Emergency Service",
        "EmploymentAgency"=>"Employment Agency",
        "EntertainmentBusiness"=>"Entertainment Business",
        "FinancialService"=>"Financial Service",
        "FoodEstablishment"=>"Food Establishment",
        "GovernmentOffice"=>"Government Office",
        "HealthAndBeautyBusiness"=>"Health and Beauty Business",
        "HomeAndConstructionBusiness"=>"Home and Construction Business",
        "InternetCafe"=>"Internet Cafe",
        "Library"=>"Library",
        "LodgingBusiness"=>"Lodging Business",
        "MedicalOrganization"=>"Medical Organization",
        "ProfessionalService"=>"Professional Service",
        "RadioStation"=>"Radio Station",
        "RealEstateAgent"=>"Real Estate Agent",
        "RecyclingCenter"=>"Recycling Center",
        "SelfStorage"=>"Self Storage",
        "ShoppingCenter"=>"Shopping Center",
        "SportsActivityLocation"=>"Sports Activity Location",
        "Store"=>"Store",
        "TelevisionStation"=>"Television Station",
        "TouristInformationCenter"=>"Tourist Information Center",
        "TravelAgency"=>"Travel Agency"
    );
  echo json_encode( $orgs, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ).PHP_EOL;  
?>